Upgrade dev deps to be compatible with net-ssh 5.0
This fixes the following error when running `rake test:functional`:

    NotImplementedError: unsupported key type `ssh-ed25519'
    net-ssh requires the following gems for ed25519 support:
     * ed25519 (>= 1.2, < 2.0)
     * bcrypt_pbkdf (>= 1.0, < 2.0)
    See https://github.com/net-ssh/net-ssh/issues/565 for more information
    Gem::LoadError : "ed25519 is not part of the bundle. Add it to your Gemfile."